---
version: 3
tasks:
  build: go build -o build/frankenrepo {{.CLI_ARGS}} .
  run: go run . {{.CLI_ARGS}}
  test: go test {{.CLI_ARGS}} ./...
  debug: dlv debug -- {{.CLI_ARGS}}

  test-c_rust:
    cmds:
      - cd test/integration/c_rust/exe/cproj; make clean
      - cd test/integration/c_rust/lib/rustproj; cargo clean
      - go run . -C test/integration/c_rust test
